import type { Metadata } from "next";
import { Suspense } from "react";
import { ChakraProvider } from "@chakra-ui/react";

export const metadata: Metadata = {
  title: "Divorce test",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: string }>;
}>) {
  return (
    <html>
      <body>
        <LanguageSwitcher>
          <ChakraProvider>{children}</ChakraProvider>
        </LanguageSwitcher>
      </body>
    </html>
  );
}

function LanguageSwitcher({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <Suspense fallback={null}>{children}</Suspense>;
}
